export default [
  {
    id: 1,
    name: "Ian Sorell",
    position: "CEO",
    description:
      "Enjoys adventurous travel, seeks new cultures and offbeat destinations",
    img: "../../../../id1.png",
    alt: "Ian Sorell",
    github: "",
    linkedin: "",
    facebook: "",
  },
  {
    id: 2,
    name: "Maya Matt",
    position: "Founder",
    description: "Pop music lover, seeks joy and exciting pop concerts",
    img: "../../../../id2.png",
    alt: "Maya Matt",
    github: "",
    linkedin: "",
    facebook: "",
  },
  {
    id: 3,
    name: "Alex Jensen",
    position: "CTO",
    description: "Bookworm, creative software developer with precision",
    img: "../../../../id2.png",
    alt: "Alex Jensen",
    github: "",
    linkedin: "",
    facebook: "",
  },
  {
    id: 4,
    name: "Keira Battye",
    position: "Product Designer",
    description: "Creative painter capturing beauty with imaginative artwork",
    img: "../../../../id4.png",
    alt: "Keira Battye",
    github: "",
    linkedin: "",
    facebook: "",
  },
  {
    id: 5,
    name: "Dominic Game",
    position: "3D Artist",
    description: "Football enthusiast, enjoys movie nights with friends",
    img: "../../../../id5.png",
    alt: "Dominic Game",
    github: "",
    linkedin: "",
    facebook: "",
  },
  {
    id: 6,
    name: "James Vial",
    position: "Head of Front-End",
    description:
      "Culinary artist, explores diverse flavors, skilled in cooking",
    img: "../../../../id6.png",
    alt: "James Vial",
    github: "",
    linkedin: "",
    facebook: "",
  },
];
